title: Test Code
author: Sushant Kumar Singh
theme: minima
email: sushant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blogging space

# social links
twitter_username: @sushant1887
github_username:  @maverick2012

show_excerpts: true # set to false to remove excerpts on the homepage
